# Generated by Django 2.1.1 on 2018-09-30 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studdybuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matchedUserID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
