# Generated by Django 2.1.1 on 2018-10-01 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studdybuddy', '0003_auto_20180930_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
