# Generated by Django 2.0.2 on 2018-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studdybuddy', '0005_auto_20181007_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='study_path',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('ID', 'Interaction Design'), ('PM', 'Product Management')], default='SE', max_length=50),
        ),
    ]
